package Gioco;

public enum TipoTessera {
    SCUDO,
    CABINA,
    PROPULSORE_SINGOLO,
    PROPULSORE_DOPPIO,
    CANNONE_SINGOLO,
    CANNONE_DOPPIO,
    BATTERIA,
    STIVA,
    STIVA_SPECIALE,
    MODULI_VITALI_MARRONI,
    MODULI_VITALI_VIOLA,
    MODULI_STRUTTURALI;
}

